/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PackagingRouteImport } from './routes/packaging'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagingIndexRouteImport } from './routes/packaging.index'
import { Route as LogisticsIndexRouteImport } from './routes/logistics.index'
import { Route as FleetIndexRouteImport } from './routes/fleet.index'
import { Route as PackagingServicesRouteImport } from './routes/packaging.services'
import { Route as PackagingIndustriesRouteImport } from './routes/packaging.industries'
import { Route as PackagingCorrugatedRouteImport } from './routes/packaging.corrugated'
import { Route as PackagingContactRouteImport } from './routes/packaging.contact'
import { Route as PackagingAboutRouteImport } from './routes/packaging.about'
import { Route as LogisticsServicesRouteImport } from './routes/logistics.services'
import { Route as LogisticsQuoteRouteImport } from './routes/logistics.quote'
import { Route as LogisticsContactRouteImport } from './routes/logistics.contact'
import { Route as LogisticsAboutRouteImport } from './routes/logistics.about'
import { Route as FleetVehiclesRouteImport } from './routes/fleet.vehicles'
import { Route as FleetServicesRouteImport } from './routes/fleet.services'
import { Route as FleetIndustriesRouteImport } from './routes/fleet.industries'
import { Route as FleetContactRouteImport } from './routes/fleet.contact'
import { Route as FleetAboutRouteImport } from './routes/fleet.about'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingRoute = PackagingRouteImport.update({
  id: '/packaging',
  path: '/packaging',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingIndexRoute = PackagingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagingRoute,
} as any)
const LogisticsIndexRoute = LogisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogisticsRoute,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FleetRoute,
} as any)
const PackagingServicesRoute = PackagingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PackagingRoute,
} as any)
const PackagingIndustriesRoute = PackagingIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => PackagingRoute,
} as any)
const PackagingCorrugatedRoute = PackagingCorrugatedRouteImport.update({
  id: '/corrugated',
  path: '/corrugated',
  getParentRoute: () => PackagingRoute,
} as any)
const PackagingContactRoute = PackagingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PackagingRoute,
} as any)
const PackagingAboutRoute = PackagingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PackagingRoute,
} as any)
const LogisticsServicesRoute = LogisticsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LogisticsRoute,
} as any)
const LogisticsQuoteRoute = LogisticsQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => LogisticsRoute,
} as any)
const LogisticsContactRoute = LogisticsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LogisticsRoute,
} as any)
const LogisticsAboutRoute = LogisticsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LogisticsRoute,
} as any)
const FleetVehiclesRoute = FleetVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => FleetRoute,
} as any)
const FleetServicesRoute = FleetServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => FleetRoute,
} as any)
const FleetIndustriesRoute = FleetIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => FleetRoute,
} as any)
const FleetContactRoute = FleetContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => FleetRoute,
} as any)
const FleetAboutRoute = FleetAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => FleetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRouteWithChildren
  '/logistics': typeof LogisticsRouteWithChildren
  '/packaging': typeof PackagingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/fleet/about': typeof FleetAboutRoute
  '/fleet/contact': typeof FleetContactRoute
  '/fleet/industries': typeof FleetIndustriesRoute
  '/fleet/services': typeof FleetServicesRoute
  '/fleet/vehicles': typeof FleetVehiclesRoute
  '/logistics/about': typeof LogisticsAboutRoute
  '/logistics/contact': typeof LogisticsContactRoute
  '/logistics/quote': typeof LogisticsQuoteRoute
  '/logistics/services': typeof LogisticsServicesRoute
  '/packaging/about': typeof PackagingAboutRoute
  '/packaging/contact': typeof PackagingContactRoute
  '/packaging/corrugated': typeof PackagingCorrugatedRoute
  '/packaging/industries': typeof PackagingIndustriesRoute
  '/packaging/services': typeof PackagingServicesRoute
  '/fleet/': typeof FleetIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/packaging/': typeof PackagingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/fleet/about': typeof FleetAboutRoute
  '/fleet/contact': typeof FleetContactRoute
  '/fleet/industries': typeof FleetIndustriesRoute
  '/fleet/services': typeof FleetServicesRoute
  '/fleet/vehicles': typeof FleetVehiclesRoute
  '/logistics/about': typeof LogisticsAboutRoute
  '/logistics/contact': typeof LogisticsContactRoute
  '/logistics/quote': typeof LogisticsQuoteRoute
  '/logistics/services': typeof LogisticsServicesRoute
  '/packaging/about': typeof PackagingAboutRoute
  '/packaging/contact': typeof PackagingContactRoute
  '/packaging/corrugated': typeof PackagingCorrugatedRoute
  '/packaging/industries': typeof PackagingIndustriesRoute
  '/packaging/services': typeof PackagingServicesRoute
  '/fleet': typeof FleetIndexRoute
  '/logistics': typeof LogisticsIndexRoute
  '/packaging': typeof PackagingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRouteWithChildren
  '/logistics': typeof LogisticsRouteWithChildren
  '/packaging': typeof PackagingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/fleet/about': typeof FleetAboutRoute
  '/fleet/contact': typeof FleetContactRoute
  '/fleet/industries': typeof FleetIndustriesRoute
  '/fleet/services': typeof FleetServicesRoute
  '/fleet/vehicles': typeof FleetVehiclesRoute
  '/logistics/about': typeof LogisticsAboutRoute
  '/logistics/contact': typeof LogisticsContactRoute
  '/logistics/quote': typeof LogisticsQuoteRoute
  '/logistics/services': typeof LogisticsServicesRoute
  '/packaging/about': typeof PackagingAboutRoute
  '/packaging/contact': typeof PackagingContactRoute
  '/packaging/corrugated': typeof PackagingCorrugatedRoute
  '/packaging/industries': typeof PackagingIndustriesRoute
  '/packaging/services': typeof PackagingServicesRoute
  '/fleet/': typeof FleetIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/packaging/': typeof PackagingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/fleet'
    | '/logistics'
    | '/packaging'
    | '/privacy'
    | '/terms'
    | '/fleet/about'
    | '/fleet/contact'
    | '/fleet/industries'
    | '/fleet/services'
    | '/fleet/vehicles'
    | '/logistics/about'
    | '/logistics/contact'
    | '/logistics/quote'
    | '/logistics/services'
    | '/packaging/about'
    | '/packaging/contact'
    | '/packaging/corrugated'
    | '/packaging/industries'
    | '/packaging/services'
    | '/fleet/'
    | '/logistics/'
    | '/packaging/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/fleet/about'
    | '/fleet/contact'
    | '/fleet/industries'
    | '/fleet/services'
    | '/fleet/vehicles'
    | '/logistics/about'
    | '/logistics/contact'
    | '/logistics/quote'
    | '/logistics/services'
    | '/packaging/about'
    | '/packaging/contact'
    | '/packaging/corrugated'
    | '/packaging/industries'
    | '/packaging/services'
    | '/fleet'
    | '/logistics'
    | '/packaging'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/fleet'
    | '/logistics'
    | '/packaging'
    | '/privacy'
    | '/terms'
    | '/fleet/about'
    | '/fleet/contact'
    | '/fleet/industries'
    | '/fleet/services'
    | '/fleet/vehicles'
    | '/logistics/about'
    | '/logistics/contact'
    | '/logistics/quote'
    | '/logistics/services'
    | '/packaging/about'
    | '/packaging/contact'
    | '/packaging/corrugated'
    | '/packaging/industries'
    | '/packaging/services'
    | '/fleet/'
    | '/logistics/'
    | '/packaging/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FleetRoute: typeof FleetRouteWithChildren
  LogisticsRoute: typeof LogisticsRouteWithChildren
  PackagingRoute: typeof PackagingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging': {
      id: '/packaging'
      path: '/packaging'
      fullPath: '/packaging'
      preLoaderRoute: typeof PackagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging/': {
      id: '/packaging/'
      path: '/'
      fullPath: '/packaging/'
      preLoaderRoute: typeof PackagingIndexRouteImport
      parentRoute: typeof PackagingRoute
    }
    '/logistics/': {
      id: '/logistics/'
      path: '/'
      fullPath: '/logistics/'
      preLoaderRoute: typeof LogisticsIndexRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof FleetRoute
    }
    '/packaging/services': {
      id: '/packaging/services'
      path: '/services'
      fullPath: '/packaging/services'
      preLoaderRoute: typeof PackagingServicesRouteImport
      parentRoute: typeof PackagingRoute
    }
    '/packaging/industries': {
      id: '/packaging/industries'
      path: '/industries'
      fullPath: '/packaging/industries'
      preLoaderRoute: typeof PackagingIndustriesRouteImport
      parentRoute: typeof PackagingRoute
    }
    '/packaging/corrugated': {
      id: '/packaging/corrugated'
      path: '/corrugated'
      fullPath: '/packaging/corrugated'
      preLoaderRoute: typeof PackagingCorrugatedRouteImport
      parentRoute: typeof PackagingRoute
    }
    '/packaging/contact': {
      id: '/packaging/contact'
      path: '/contact'
      fullPath: '/packaging/contact'
      preLoaderRoute: typeof PackagingContactRouteImport
      parentRoute: typeof PackagingRoute
    }
    '/packaging/about': {
      id: '/packaging/about'
      path: '/about'
      fullPath: '/packaging/about'
      preLoaderRoute: typeof PackagingAboutRouteImport
      parentRoute: typeof PackagingRoute
    }
    '/logistics/services': {
      id: '/logistics/services'
      path: '/services'
      fullPath: '/logistics/services'
      preLoaderRoute: typeof LogisticsServicesRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/logistics/quote': {
      id: '/logistics/quote'
      path: '/quote'
      fullPath: '/logistics/quote'
      preLoaderRoute: typeof LogisticsQuoteRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/logistics/contact': {
      id: '/logistics/contact'
      path: '/contact'
      fullPath: '/logistics/contact'
      preLoaderRoute: typeof LogisticsContactRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/logistics/about': {
      id: '/logistics/about'
      path: '/about'
      fullPath: '/logistics/about'
      preLoaderRoute: typeof LogisticsAboutRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/fleet/vehicles': {
      id: '/fleet/vehicles'
      path: '/vehicles'
      fullPath: '/fleet/vehicles'
      preLoaderRoute: typeof FleetVehiclesRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/services': {
      id: '/fleet/services'
      path: '/services'
      fullPath: '/fleet/services'
      preLoaderRoute: typeof FleetServicesRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/industries': {
      id: '/fleet/industries'
      path: '/industries'
      fullPath: '/fleet/industries'
      preLoaderRoute: typeof FleetIndustriesRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/contact': {
      id: '/fleet/contact'
      path: '/contact'
      fullPath: '/fleet/contact'
      preLoaderRoute: typeof FleetContactRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/about': {
      id: '/fleet/about'
      path: '/about'
      fullPath: '/fleet/about'
      preLoaderRoute: typeof FleetAboutRouteImport
      parentRoute: typeof FleetRoute
    }
  }
}

interface FleetRouteChildren {
  FleetAboutRoute: typeof FleetAboutRoute
  FleetContactRoute: typeof FleetContactRoute
  FleetIndustriesRoute: typeof FleetIndustriesRoute
  FleetServicesRoute: typeof FleetServicesRoute
  FleetVehiclesRoute: typeof FleetVehiclesRoute
  FleetIndexRoute: typeof FleetIndexRoute
}

const FleetRouteChildren: FleetRouteChildren = {
  FleetAboutRoute: FleetAboutRoute,
  FleetContactRoute: FleetContactRoute,
  FleetIndustriesRoute: FleetIndustriesRoute,
  FleetServicesRoute: FleetServicesRoute,
  FleetVehiclesRoute: FleetVehiclesRoute,
  FleetIndexRoute: FleetIndexRoute,
}

const FleetRouteWithChildren = FleetRoute._addFileChildren(FleetRouteChildren)

interface LogisticsRouteChildren {
  LogisticsAboutRoute: typeof LogisticsAboutRoute
  LogisticsContactRoute: typeof LogisticsContactRoute
  LogisticsQuoteRoute: typeof LogisticsQuoteRoute
  LogisticsServicesRoute: typeof LogisticsServicesRoute
  LogisticsIndexRoute: typeof LogisticsIndexRoute
}

const LogisticsRouteChildren: LogisticsRouteChildren = {
  LogisticsAboutRoute: LogisticsAboutRoute,
  LogisticsContactRoute: LogisticsContactRoute,
  LogisticsQuoteRoute: LogisticsQuoteRoute,
  LogisticsServicesRoute: LogisticsServicesRoute,
  LogisticsIndexRoute: LogisticsIndexRoute,
}

const LogisticsRouteWithChildren = LogisticsRoute._addFileChildren(
  LogisticsRouteChildren,
)

interface PackagingRouteChildren {
  PackagingAboutRoute: typeof PackagingAboutRoute
  PackagingContactRoute: typeof PackagingContactRoute
  PackagingCorrugatedRoute: typeof PackagingCorrugatedRoute
  PackagingIndustriesRoute: typeof PackagingIndustriesRoute
  PackagingServicesRoute: typeof PackagingServicesRoute
  PackagingIndexRoute: typeof PackagingIndexRoute
}

const PackagingRouteChildren: PackagingRouteChildren = {
  PackagingAboutRoute: PackagingAboutRoute,
  PackagingContactRoute: PackagingContactRoute,
  PackagingCorrugatedRoute: PackagingCorrugatedRoute,
  PackagingIndustriesRoute: PackagingIndustriesRoute,
  PackagingServicesRoute: PackagingServicesRoute,
  PackagingIndexRoute: PackagingIndexRoute,
}

const PackagingRouteWithChildren = PackagingRoute._addFileChildren(
  PackagingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FleetRoute: FleetRouteWithChildren,
  LogisticsRoute: LogisticsRouteWithChildren,
  PackagingRoute: PackagingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
